// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxdroeloeynetqcoltfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZHJvZWxvZXluZXRxY29sdGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTA4NDcsImV4cCI6MjA1OTc2Njg0N30.13ZbqPYnmQ8i2rbnzCqAE8nDZLXyIkegoRlZGjtbiBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);